/**
 * Public TianGong Community records follow the published Wix ordering.
 * Partner institutions follow the source workbook row order.
 * Private workbook contact fields are intentionally excluded.
 */
export const domainExperts = [
  {
    slug: "zhi-cao-e0c924",
    name: "Zhi Cao",
    affiliationZh: "南开大学",
    affiliationEn: "Nankai University",
    domainZh: "水泥、沥青",
    domainEn: "Cement, Asphalt",
    email: "zhicao@nankai.edu.cn",
    image: "/community/experts/zhi-cao-e0c924.webp",
  },
  {
    slug: "tan-chen-90bff8",
    name: "Tan Chen",
    affiliationZh: "中央民族大学",
    affiliationEn: "Minzu University of China",
    domainZh: "生活垃圾全过程管理",
    domainEn: "Integrated process management of municipal solid waste",
    email: "chentan05@tsinghua.org.cn",
    image: "/community/experts/tan-chen-90bff8.webp",
  },
  {
    slug: "weiqiang-chen-f80bec",
    name: "Weiqiang Chen",
    affiliationZh: "中国科学院城市环境研究所",
    affiliationEn: "IUE, CAS",
    domainZh: "有色金属",
    domainEn: "Nonferrous Metal",
    email: "wqchen@iue.ac.cn",
    image: "/community/experts/weiqiang-chen-f80bec.webp",
  },
  {
    slug: "chang-chen-f87052",
    name: "Chang Chen",
    affiliationZh: "华中农业大学",
    affiliationEn: "Huazhong Agricultural University",
    domainZh: "水果、蔬菜、坚果",
    domainEn: "Fruit, Vegetables, Nut",
    email: "changchen@mail.hzau.edu.cn",
    image: "/community/experts/chang-chen-f87052.webp",
  },
  {
    slug: "jianwei-du-996143",
    name: "Jianwei Du",
    affiliationZh: "生态环境部华南环境科学研究所",
    affiliationEn: "South China Institute of Environmental Science",
    domainZh: "重金属污染防控与循环经济",
    domainEn: "Heavy Metal Pollution Prevention and Control, Circular Economy",
    email: "dujianwei@scies.org",
    image: "/community/experts/jianwei-du-996143.webp",
  },
  {
    slug: "huabo-duan-50a83b",
    name: "Huabo Duan",
    affiliationZh: "华中科技大学",
    affiliationEn: "Huazhong University of Science and Technology",
    domainZh: "工业固体废物",
    domainEn: "Industrial Solid Waste",
    email: "huabo@hust.edu.cn",
    image: "/community/experts/huabo-duan-50a83b.webp",
  },
  {
    slug: "kai-fang-9fc95d",
    name: "Kai Fang",
    affiliationZh: "浙江大学",
    affiliationEn: "Zhejiang University",
    domainZh: "",
    domainEn: "",
    email: "fangk@zju.edu.cn",
    image: "/community/experts/kai-fang-9fc95d.webp",
  },
  {
    slug: "cuiyang-feng-23c177",
    name: "Cuiyang Feng",
    affiliationZh: "中国矿业大学（北京）",
    affiliationEn: "China University of Mining & Technology - Beijing",
    domainZh: "化石燃料生产",
    domainEn: "Fossil fuel production",
    email: "fengcuiyang@163.com",
    image: "/community/experts/cuiyang-feng-23c177.webp",
  },
  {
    slug: "xiaofeng-gao-496139",
    name: "Xiaofeng Gao",
    affiliationZh: "重庆大学",
    affiliationEn: "Chongqing University",
    domainZh: "",
    domainEn: "",
    email: null,
    image: "/community/experts/xiaofeng-gao-496139.webp",
  },
  {
    slug: "meiyu-guo-6891c9",
    name: "Meiyu Guo",
    affiliationZh: "香港浸会大学",
    affiliationEn: "Hong Kong Baptist University",
    domainZh: "页岩气",
    domainEn: "Shale Gas",
    email: "meiyuguo@hkbu.edu.hk",
    image: "/community/experts/meiyu-guo-6891c9.webp",
  },
  {
    slug: "miao-he-840395",
    name: "Miao He",
    affiliationZh: "河北大学",
    affiliationEn: "Hebei University",
    domainZh: "水电",
    domainEn: "水电",
    email: "miaohewendy@126.com",
    image: "/community/experts/miao-he-840395.webp",
  },
  {
    slug: "yuanchao-hu-786b68",
    name: "Yuanchao Hu",
    affiliationZh: "武汉大学",
    affiliationEn: "Wuhan University",
    domainZh: "作物、畜禽",
    domainEn: "Crops, Livestock and Poultry",
    email: "yuanchao.hu@whu.edu.cn",
    image: "/community/experts/yuanchao-hu-786b68.webp",
  },
  {
    slug: "beijia-huang-24db8c",
    name: "Beijia Huang",
    affiliationZh: "上海理工大学",
    affiliationEn: "University of Shanghai for Science and Technology",
    domainZh: "砖块、玻璃、沙石",
    domainEn: "Brick, Glass, Crushed Stone, Sand",
    email: "ywhbjia@163.com",
    image: "/community/experts/beijia-huang-24db8c.webp",
  },
  {
    slug: "chengjiang-li-1a38ec",
    name: "Chengjiang Li",
    affiliationZh: "贵州大学",
    affiliationEn: "Guizhou University",
    domainZh: "汽车",
    domainEn: "汽车",
    email: null,
    image: "/community/experts/chengjiang-li-1a38ec.webp",
  },
  {
    slug: "jiashuo-li-239499",
    name: "Jiashuo Li",
    affiliationZh: "山东大学",
    affiliationEn: "Shandong University",
    domainZh: "能源清洁低碳转型管理",
    domainEn: "Energy Clean and Low-carbon Transition Management",
    email: "lijiashuo@sdu.edu.cn",
    image: "/community/experts/jiashuo-li-239499.webp",
  },
  {
    slug: "hui-li-9e7fad",
    name: "Hui Li",
    affiliationZh: "北京师范大学",
    affiliationEn: "Beijing Normal University",
    domainZh: "火电、光电、食品行业",
    domainEn: "Thermal power, Solar power, food",
    email: "lihuui@bnu.edu.cn",
    image: "/community/experts/hui-li-9e7fad.webp",
  },
  {
    slug: "shaobing-li-e31cd6",
    name: "Shaobing Li",
    affiliationZh: "厦门大学",
    affiliationEn: "Xiamen University",
    domainZh: "食物系统生命周期评价、陆海统筹与可持续发展",
    domainEn: "Food Systems, Land and Sea Integration and Sustainable Development",
    email: "shaobinli@xmu.edu.cn",
    image: "/community/experts/shaobing-li-e31cd6.webp",
  },
  {
    slug: "fengqin-liu-043790",
    name: "Fengqin Liu",
    affiliationZh: "北京科技大学",
    affiliationEn: "University of Science and Technology Beijing",
    domainZh: "铝",
    domainEn: "Aluminum production",
    email: "liufq@ustb.edu.cn",
    image: "/community/experts/fengqin-liu-043790.webp",
  },
  {
    slug: "jiaqi-lu-569c40",
    name: "Jiaqi Lu",
    affiliationZh: "上海工程技术大学",
    affiliationEn: "Shanghai University Of Engineering Science",
    domainZh: "焚烧、废塑料化学回收",
    domainEn: "Incineration and Chemical Recycling of Waste Plastics",
    email: "04200011@sues.edu.cn",
    image: "/community/experts/jiaqi-lu-569c40.webp",
  },
  {
    slug: "zhongming-lu-62d0b7",
    name: "Zhongming Lu",
    affiliationZh: "香港科技大学",
    affiliationEn: "The Hong Kong University of Science and Technology",
    domainZh: "氨气合成",
    domainEn: "Ammonia",
    email: "zhongminglu@ust.hk",
    image: "/community/experts/zhongming-lu-62d0b7.webp",
  },
  {
    slug: "weichun-ma-a47c49",
    name: "Weichun Ma",
    affiliationZh: "复旦大学",
    affiliationEn: "Fudan University",
    domainZh: "",
    domainEn: "",
    email: "wcma@fudan.edu.cn",
    image: "/community/experts/weichun-ma-a47c49.webp",
  },
  {
    slug: "guozhu-mao-fe3690",
    name: "Guozhu Mao",
    affiliationZh: "天津大学",
    affiliationEn: "Tianjin University",
    domainZh: "废水处理、电能、新能源材料等",
    domainEn: "废水处理、电能、新能源材料等",
    email: "maoguozhu@tju.edu.cn",
    image: "/community/experts/guozhu-mao-fe3690.webp",
  },
  {
    slug: "fanran-meng-c01114",
    name: "Fanran Meng",
    affiliationZh: "谢菲尔德大学",
    affiliationEn: "University of Sheffield",
    domainZh: "动力电池，化工",
    domainEn: "Power battery, Chemical engineering",
    email: "f.meng@sheffield.ac.uk",
    image: "/community/experts/fanran-meng-c01114.webp",
  },
  {
    slug: "yanan-ren-cd0125",
    name: "Yanan Ren",
    affiliationZh: "南京航空航天大学",
    affiliationEn: "Nanjing University of Aeronautics and Astronautics",
    domainZh: "化学品",
    domainEn: "Chemicals",
    email: "yanan_ren@nuaa.edu.cn",
    image: "/community/experts/yanan-ren-cd0125.webp",
  },
  {
    slug: "lei-shi-0278db",
    name: "Lei Shi",
    affiliationZh: "南昌大学",
    affiliationEn: "Nanchang University",
    domainZh: "塑料",
    domainEn: "Plastics",
    email: "shilei@ncu.edu.cn",
    image: "/community/experts/lei-shi-0278db.webp",
  },
  {
    slug: "junnian-song-a93a94",
    name: "Junnian Song",
    affiliationZh: "吉林大学",
    affiliationEn: "Jilin University",
    domainZh: "食物、农业与生物质",
    domainEn: "Food，Agriculture and Biomass",
    email: "songjunnian@jlu.edu.cn",
    image: "/community/experts/junnian-song-a93a94.webp",
  },
  {
    slug: "guobao-song-e6976a",
    name: "Guobao Song",
    affiliationZh: "大连理工大学",
    affiliationEn: "Dalian University of Technology",
    domainZh: "海藻、人工鱼礁",
    domainEn: "Seaweed, Artificial reef",
    email: "gb.song@dlut.edu.cn",
    image: "/community/experts/guobao-song-e6976a.webp",
  },
  {
    slug: "mingxing-sun-8106d7",
    name: "Mingxing Sun",
    affiliationZh: "中国科学院地理科学与资源研究所",
    affiliationEn: "IGSNRR, CAS",
    domainZh: "航空燃油",
    domainEn: "Bio-jet fuel",
    email: "sunmx@igsnrr.ac.cn",
    image: "/community/experts/mingxing-sun-8106d7.webp",
  },
  {
    slug: "xin-sun-87a0fc",
    name: "Xin Sun",
    affiliationZh: "康奈尔大学",
    affiliationEn: "University of Groningen",
    domainZh: "锂电池",
    domainEn: "Lithium-ion Battery, Critical Material",
    email: "xin.sun@rug.nl",
    image: "/community/experts/xin-sun-87a0fc.webp",
  },
  {
    slug: "lu-sun-9475b8",
    name: "Lu Sun",
    affiliationZh: "西安交通大学",
    affiliationEn: "Xi’an Jiaotong University",
    domainZh: "热能、生铁、水泥砂浆、水泥瓦",
    domainEn: "Thermal energy，raw iron，concrete mortar, cement tiles",
    email: "sunlu2021@126.com",
    image: "/community/experts/lu-sun-9475b8.webp",
  },
  {
    slug: "chuanwang-sun-e67578",
    name: "Chuanwang Sun",
    affiliationZh: "厦门大学",
    affiliationEn: "Xiamen University",
    domainZh: "",
    domainEn: "",
    email: "cw_sun@foxmail.com",
    image: "/community/experts/chuanwang-sun-e67578.webp",
  },
  {
    slug: "jinping-tian-5553ef",
    name: "Jinping Tian",
    affiliationZh: "清华大学",
    affiliationEn: "Tsinghua University",
    domainZh: "染料、农药、锂电池",
    domainEn: "Dye, Pesticide, Lithium-ion Battery",
    email: "tianjp@tsinghua.edu.cn",
    image: "/community/experts/jinping-tian-5553ef.webp",
  },
  {
    slug: "xi-tian-b78519",
    name: "Xi Tian",
    affiliationZh: "南昌大学",
    affiliationEn: "Nanchang University",
    domainZh: "锂电池",
    domainEn: "Lithium-ion Battery",
    email: "txindustry@163.com",
    image: "/community/experts/xi-tian-b78519.webp",
  },
  {
    slug: "qingshi-tu-49b93e",
    name: "Qingshi Tu",
    affiliationZh: "英属哥伦比亚大学",
    affiliationEn: "University of British Columbia",
    domainZh: "氢能源，林产品，生物质化学品，生物质材料",
    domainEn: "Hydrogen Energy, Wood Products, Biochemicals, Biomaterials",
    email: "qingshi.tu@ubc.ca",
    image: "/community/experts/qingshi-tu-49b93e.webp",
  },
  {
    slug: "heming-wang-82a3c3",
    name: "Heming Wang",
    affiliationZh: "东北大学",
    affiliationEn: "Northeastern University",
    domainZh: "橡胶/输电网",
    domainEn: "Rubber, Electricity Transmission Grid",
    email: "wanghm@mail.neu.edu.cn",
    image: "/community/experts/heming-wang-82a3c3.webp",
  },
  {
    slug: "zhen-wang-986dc8",
    name: "Zhen Wang",
    affiliationZh: "北京林业大学",
    affiliationEn: "Beijing Forestry University",
    domainZh: "林产品，塑料",
    domainEn: "Forest products, plastics",
    email: "wangzhen@bjfu.edu.cn",
    image: "/community/experts/zhen-wang-986dc8.webp",
  },
  {
    slug: "hongtao-wang-e15499",
    name: "Hongtao Wang",
    affiliationZh: "同济大学",
    affiliationEn: "Tongji University",
    domainZh: "污水处理厂",
    domainEn: "Wastewater Treatment",
    email: "hongtao@tongji.edu.cn",
    image: "/community/experts/hongtao-wang-e15499.webp",
  },
  {
    slug: "laili-wang-e1d4d5",
    name: "Laili Wang",
    affiliationZh: "浙江理工大学",
    affiliationEn: "Zhejiang Sci-Tech University",
    domainZh: "纺织",
    domainEn: "Textile",
    email: "wangll@zstu.edu.cn",
    image: "/community/experts/laili-wang-e1d4d5.webp",
  },
  {
    slug: "yutao-wang-fc43f3",
    name: "Yutao Wang",
    affiliationZh: "复旦大学",
    affiliationEn: "Fudan University",
    domainZh: "造纸、纺织",
    domainEn: "Pulping and Papermaking; Spinning and Weaving",
    email: "yutaowang@fudan.edu.cn",
    image: "/community/experts/yutao-wang-fc43f3.webp",
  },
  {
    slug: "jiwei-wu-27ae97",
    name: "Jiwei Wu",
    affiliationZh: "四川大学",
    affiliationEn: "Sichuan University",
    domainZh: "含油污泥处理",
    domainEn: "Oily sludge treatment",
    email: "wu_jiwei@scu.edu.cn",
    image: "/community/experts/jiwei-wu-27ae97.webp",
  },
  {
    slug: "fan-wu-906e02",
    name: "Fan Wu",
    affiliationZh: "暨南大学",
    affiliationEn: "Jinan University",
    domainZh: "页岩气、抽水储能、农药",
    domainEn: "Shale gas, Pumped hydro energy storage，Pesticde",
    email: "fanwu@jnu.edu.cn",
    image: "/community/experts/fan-wu-906e02.webp",
  },
  {
    slug: "minghui-xie-8290eb",
    name: "Minghui Xie",
    affiliationZh: "中国环境科学研究院",
    affiliationEn: "Chinese Research Academy of Environmental Sciences",
    domainZh: "光伏",
    domainEn: "Photovoltaic",
    email: "xiemh@craes.org.cn",
    image: "/community/experts/minghui-xie-8290eb.webp",
  },
  {
    slug: "chunlin-xin-95e94f",
    name: "Chunlin Xin",
    affiliationZh: "北京化工大学",
    affiliationEn: "Beijing University of Chemical Technology",
    domainZh: "医药行业",
    domainEn: "biological medicine",
    email: "xinchl@buct.edu.cn",
    image: "/community/experts/chunlin-xin-95e94f.webp",
  },
  {
    slug: "changqing-xu-2df1bb",
    name: "Changqing Xu",
    affiliationZh: "北京理工大学",
    affiliationEn: "Beijing Institute of Technology",
    domainZh: "再生水、雨水",
    domainEn: "Reclaimed Water, Rainwater",
    email: "xcq@bit.edu.cn",
    image: "/community/experts/changqing-xu-2df1bb.webp",
  },
  {
    slug: "ming-xu-5a4914",
    name: "Ming Xu",
    affiliationZh: "清华大学",
    affiliationEn: "Tsinghua University",
    domainZh: "污泥、水泥、保温材料、铝、风机叶片回收",
    domainEn: "Building Material, Waste, Clean Energy Equipment",
    email: "xu-ming@tsinghua.edu.cn",
    image: "/community/experts/ming-xu-5a4914.webp",
  },
  {
    slug: "qiang-yue-2faf8d",
    name: "Qiang Yue",
    affiliationZh: "东北大学",
    affiliationEn: "Northeastern University",
    domainZh: "钢材生产",
    domainEn: "Steel production",
    email: "yueq@smm.neu.edu.cn",
    image: "/community/experts/qiang-yue-2faf8d.webp",
  },
  {
    slug: "hongzhen-zhang-110bf7",
    name: "Hongzhen Zhang",
    affiliationZh: "生态环境部环境规划院",
    affiliationEn: "Chinese Academy of Environmental Planning",
    domainZh: "土壤和地下水修复管控",
    domainEn: "Soil and Groundwater Remediation and Control",
    email: "hongzhenzhang@126.com",
    image: "/community/experts/hongzhen-zhang-110bf7.webp",
  },
  {
    slug: "lixiao-zhang-15e939",
    name: "Lixiao Zhang",
    affiliationZh: "北京师范大学",
    affiliationEn: "Beijing Normal University",
    domainZh: "小水电、粮食",
    domainEn: "Small Hydropower, Grain",
    email: "zhanglixiao@bnu.edu.cn",
    image: "/community/experts/lixiao-zhang-15e939.webp",
  },
  {
    slug: "yan-zhao-f9ae88",
    name: "Yan Zhao",
    affiliationZh: "北京师范大学",
    affiliationEn: "Beijing Normal University",
    domainZh: "城市生活垃圾",
    domainEn: "Municipal Solid Waste",
    email: "yanzhao@bnu.edu.cn",
    image: "/community/experts/yan-zhao-f9ae88.webp",
  },
  {
    slug: "ya-zhou-3ca0ab",
    name: "Ya Zhou",
    affiliationZh: "广东工业大学",
    affiliationEn: "Guangdong University of Technology",
    domainZh: "",
    domainEn: "",
    email: null,
    image: "/community/experts/ya-zhou-3ca0ab.webp",
  },
  {
    slug: "jian-zuo-0a317d",
    name: "Jian Zuo",
    affiliationZh: "阿德莱德大学",
    affiliationEn: "University of Adelaide",
    domainZh: "风力、光伏",
    domainEn: "wind power ,photovoltaic (PV) power",
    email: null,
    image: "/community/experts/jian-zuo-0a317d.webp",
  },
] as const;

export const contributors = [
  {
    slug: "zimeng-cai-5840c5",
    nameZh: "蔡梓萌",
    nameEn: "Zimeng Cai",
    affiliation: "Tsinghua University",
    topicZh: "再生水",
    topicEn: "Reclaimed water",
  },
  {
    slug: "qilin-cao-bd845a",
    nameZh: "曹琪林",
    nameEn: "Qilin Cao",
    affiliation: "Jilin University",
    topicZh: "城市生活垃圾",
    topicEn: "Municipal solid waste",
  },
  {
    slug: "huimin-chang-f2831b",
    nameZh: "常慧敏",
    nameEn: "Huimin Chang",
    affiliation: "Tsinghua University",
    topicZh: "污泥",
    topicEn: "Sewage sludge",
  },
  {
    slug: "lipeng-chen-22ca05",
    nameZh: "陈利鹏",
    nameEn: "Lipeng Chen",
    affiliation: "Nanchang University",
    topicZh: "锂电池",
    topicEn: "Lithium-ion battery",
  },
  {
    slug: "bin-chen-248062",
    nameZh: "陈斌",
    nameEn: "Bin Chen",
    affiliation: "Fudan University",
    topicZh: "制浆造纸",
    topicEn: "Pulping and Papermaking",
  },
  {
    slug: "xin-chen-5ed275",
    nameZh: "陈鑫",
    nameEn: "Xin Chen",
    affiliation: "Nankai University",
    topicZh: "动力电池",
    topicEn: "Power battery",
  },
  {
    slug: "yunchang-ding-b89543",
    nameZh: "丁韵畅",
    nameEn: "Yunchang Ding",
    affiliation: "Huazhong University of Science and Technology",
    topicZh: "工业固体废物",
    topicEn: "Industrial solid waste",
  },
  {
    slug: "yingfan-duan-a0ef07",
    nameZh: "段颖凡",
    nameEn: "Yingfan Duan",
    affiliation: "Fudan University",
    topicZh: "纺织",
    topicEn: "Spinning and weaving",
  },
  {
    slug: "yuzhen-feng-d26aed",
    nameZh: "封羽真",
    nameEn: "Yuzhen Feng",
    affiliation: "Tsinghua University",
    topicZh: "铝",
    topicEn: "Aluminum production",
  },
  {
    slug: "xiang-fu-0b656d",
    nameZh: "付翔",
    nameEn: "Xiang Fu",
    affiliation: "Northeastern University",
    topicZh: "钢材生产",
    topicEn: "Steel production",
  },
  {
    slug: "chenling-fu-1d721f",
    nameZh: "傅晨玲",
    nameEn: "Chenling Fu",
    affiliation: "Tsinghua University",
    topicZh: "电力",
    topicEn: "Power system",
  },
  {
    slug: "jinlu-gan-916b52",
    nameZh: "甘金璐",
    nameEn: "Jinlu Gan",
    affiliation: "University of British Columbia",
    topicZh: "氢能源",
    topicEn: "Hydrogen energy",
  },
  {
    slug: "yixiang-gao-1c32be",
    nameZh: "高逸翔",
    nameEn: "Yixiang Gao",
    affiliation: "Fudan University",
    topicZh: "制浆造纸",
    topicEn: "Pulping and Papermaking",
  },
  {
    slug: "yongyue-gong-8a6ffb",
    nameZh: "龚永月",
    nameEn: "Yongyue Gong",
    affiliation: "Northeastern University",
    topicZh: "输电网",
    topicEn: "Electricity transmission grid",
  },
  {
    slug: "jing-guo-150e63",
    nameZh: "郭静",
    nameEn: "Jing Guo",
    affiliation: "Tsinghua University",
    topicZh: "水泥",
    topicEn: "Cement",
  },
  {
    slug: "pu-hong-f1a9a9",
    nameZh: "洪溥",
    nameEn: "Pu Hong",
    affiliation: "Hong Kong Baptist University",
    topicZh: "页岩气",
    topicEn: "Shale gas",
  },
  {
    slug: "zhikang-hu-25c45e",
    nameZh: "胡志康",
    nameEn: "Zhikang Hu",
    affiliation: "Nanchang University",
    topicZh: "锂电池",
    topicEn: "Lithium-ion battery",
  },
  {
    slug: "wei-ji-0bb7ee",
    nameZh: "纪伟",
    nameEn: "Wei Ji",
    affiliation: "Northeastern University",
    topicZh: "钢材生产",
    topicEn: "Steel production",
  },
  {
    slug: "peijin-jiang-53a919",
    nameZh: "蒋沛锦",
    nameEn: "Peijin Jiang",
    affiliation: "University of British Columbia",
    topicZh: "氢能源",
    topicEn: "Hydrogen energy",
  },
  {
    slug: "jing-li-edb1c7",
    nameZh: "李静",
    nameEn: "Jing Li",
    affiliation: "Shandong University",
    topicZh: "光伏",
    topicEn: "Photovoltaics",
  },
  {
    slug: "yifei-liu-ec844f",
    nameZh: "刘逸飞",
    nameEn: "Yifei Liu",
    affiliation: "Huazhong University of Science and Technology",
    topicZh: "工业固体废物",
    topicEn: "Industrial solid waste",
  },
  {
    slug: "xiaotian-ma-5b76f3",
    nameZh: "马逍天",
    nameEn: "Xiaotian Ma",
    affiliation: "Shandong University",
    topicZh: "电力",
    topicEn: "Power system",
  },
  {
    slug: "qingyuan-ma-8d3c36",
    nameZh: "马清源",
    nameEn: "Qingyuan Ma",
    affiliation: "Nanchang University",
    topicZh: "锂电池",
    topicEn: "Lithium-ion battery",
  },
  {
    slug: "fei-peng-b9a751",
    nameZh: "彭菲",
    nameEn: "Fei Peng",
    affiliation: "Nanchang University",
    topicZh: "锂电池",
    topicEn: "Lithium-ion battery",
  },
  {
    slug: "jianchuan-qi-49a6ee",
    nameZh: "齐剑川",
    nameEn: "Jianchuan Qi",
    affiliation: "Tsinghua University",
    topicZh: "整体架构",
    topicEn: "整体架构",
  },
  {
    slug: "rui-song-28908f",
    nameZh: "宋睿",
    nameEn: "Rui Song",
    affiliation: "Nankai University",
    topicZh: "水泥与混凝土",
    topicEn: "Cement and Concrete",
  },
  {
    slug: "wanyue-tan-abfc10",
    nameZh: "谭惋月",
    nameEn: "Wanyue Tan",
    affiliation: "University of British Columbia",
    topicZh: "（采伐）林产品",
    topicEn: "Forest products (harvested)",
  },
  {
    slug: "zirui-tang-6bc572",
    nameZh: "唐子睿",
    nameEn: "Zirui Tang",
    affiliation: "University of British Columbia",
    topicZh: "生物基化学品",
    topicEn: "Bio-based chemical",
  },
  {
    slug: "zhaoxing-wang-0b33f5",
    nameZh: "王兆星",
    nameEn: "Zhaoxing Wang",
    affiliation: "Nankai University",
    topicZh: "道路建材产品",
    topicEn: "Road building materials",
  },
  {
    slug: "huanyu-wang-0c372a",
    nameZh: "王环宇",
    nameEn: "Huanyu Wang",
    affiliation: "Northeastern University",
    topicZh: "钢材生产",
    topicEn: "Steel production",
  },
  {
    slug: "na-wang-905910",
    nameZh: "王娜",
    nameEn: "Na Wang",
    affiliation: "Northeastern University",
    topicZh: "输电网",
    topicEn: "Electricity transmission grid",
  },
  {
    slug: "yao-wang-a0813e",
    nameZh: "王尧",
    nameEn: "Yao Wang",
    affiliation: "Northeastern University",
    topicZh: "橡胶",
    topicEn: "Rubber",
  },
  {
    slug: "ju-wang-bec60f",
    nameZh: "王菊",
    nameEn: "Ju Wang",
    affiliation: "Fudan University",
    topicZh: "纺织",
    topicEn: "Spinning and weaving",
  },
  {
    slug: "ziqi-wang-d11940",
    nameZh: "王子祺",
    nameEn: "Ziqi Wang",
    affiliation: "Tsinghua University",
    topicZh: "风机叶片回收",
    topicEn: "Wind turbine blade recycling",
  },
  {
    slug: "yuxuan-wang-fc7d5e",
    nameZh: "王宇轩",
    nameEn: "Yuxuan Wang",
    affiliation: "Northeastern University",
    topicZh: "输电网",
    topicEn: "Electricity transmission grid",
  },
  {
    slug: "jinliang-xie-88d52c",
    nameZh: "谢金良",
    nameEn: "Jinliang Xie",
    affiliation: "Tsinghua University",
    topicZh: "铝",
    topicEn: "Aluminum production",
  },
  {
    slug: "ruoxi-xiong-906a2a",
    nameZh: "熊若熙",
    nameEn: "Ruoxi Xiong",
    affiliation: "Tsinghua University",
    topicZh: "电力",
    topicEn: "Power system",
  },
  {
    slug: "feng-xu-f89c8f",
    nameZh: "徐峰",
    nameEn: "Feng Xu",
    affiliation: "Beijing University of Chemical Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "jinfeng-yang-39d114",
    nameZh: "杨锦锋",
    nameEn: "Jinfeng Yang",
    affiliation: "Shandong University",
    topicZh: "电力",
    topicEn: "Power system",
  },
  {
    slug: "siqi-yang-c7347b",
    nameZh: "杨思琪",
    nameEn: "Siqi Yang",
    affiliation: "Tsinghua University",
    topicZh: "水泥",
    topicEn: "Cement",
  },
  {
    slug: "jiayi-yuan-81bb74",
    nameZh: "袁嘉翼",
    nameEn: "Jiayi Yuan",
    affiliation: "Tsinghua University",
    topicZh: "塑料回收",
    topicEn: "Plastic recycling and Petrochemical Products",
  },
  {
    slug: "ao-zeng-efb734",
    nameZh: "曾奥",
    nameEn: "Ao Zeng",
    affiliation: "Huazhong University of Science and Technology",
    topicZh: "工业固体废物",
    topicEn: "Industrial solid waste",
  },
  {
    slug: "yunzhi-zhao-d0c4b9",
    nameZh: "赵云志",
    nameEn: "Yunzhi Zhao",
    affiliation: "Shandong University",
    topicZh: "电力",
    topicEn: "Power system",
  },
  {
    slug: "yating-zhou-734998",
    nameZh: "周雅婷",
    nameEn: "Yating Zhou",
    affiliation: "Shandong University",
    topicZh: "光伏",
    topicEn: "Photovoltaics",
  },
  {
    slug: "qiuxia-zou-94d7b5",
    nameZh: "邹秋霞",
    nameEn: "Qiuxia Zou",
    affiliation: "Huazhong University of Science and Technology",
    topicZh: "工业固废",
    topicEn: "Industrial solid waste",
  },
  {
    slug: "yiqing-cao-32d8a6",
    nameZh: "曹已晴",
    nameEn: "Yiqing Cao",
    affiliation: "Beijing University of Chemical Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "hanshi-chen-1595a6",
    nameZh: "陈晗施",
    nameEn: "Hanshi Chen",
    affiliation: "IUE, CAS",
    topicZh: "铜",
    topicEn: "Copper",
  },
  {
    slug: "kehao-chen-521915",
    nameZh: "陈柯澔",
    nameEn: "Kehao Chen",
    affiliation: "University of Adelaide",
    topicZh: "风力、光伏",
    topicEn: "Wind, photovoltaic",
  },
  {
    slug: "siyuan-chen-8a51db",
    nameZh: "陈思源",
    nameEn: "Siyuan Chen",
    affiliation: "Zhejiang University",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "keyan-chen-aa2e4e",
    nameZh: "陈科言",
    nameEn: "Keyan Chen",
    affiliation: "Jinan University",
    topicZh: "页岩气",
    topicEn: "Shale gas",
  },
  {
    slug: "zhihao-chen-ea8b73",
    nameZh: "陈郅昊",
    nameEn: "Zhihao Chen",
    affiliation: "USST",
    topicZh: "建材",
    topicEn: "Building materials",
  },
  {
    slug: "zihan-cheng-62979e",
    nameZh: "程子涵",
    nameEn: "Zihan Cheng",
    affiliation: "Dalian University of Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "xiaoyu-cheng-6aa8fb",
    nameZh: "程晓宇",
    nameEn: "Xiaoyu Cheng",
    affiliation: "Nanchang University",
    topicZh: "塑料",
    topicEn: "Plastics",
  },
  {
    slug: "siyang-chen-a466d4",
    nameZh: "陈思杨",
    nameEn: "Siyang Chen",
    affiliation: "South China Institute of Environmental Science",
    topicZh: "填埋",
    topicEn: "Landfilling",
  },
  {
    slug: "di-cui-43e406",
    nameZh: "崔笛",
    nameEn: "Di Cui",
    affiliation: "Northeastern University",
    topicZh: "橡胶",
    topicEn: "Rubber",
  },
  {
    slug: "mingli-cui-de3583",
    nameZh: "崔茗莉",
    nameEn: "Mingli Cui",
    affiliation: "China University of Geosciences Beijing",
    topicZh: "能源低碳政策与电力市场",
    topicEn: "Low-carbon energy policy and electricity market",
  },
  {
    slug: "mengyuan-dang-0feaeb",
    nameZh: "党梦园",
    nameEn: "Mengyuan Dang",
    affiliation: "IUE, CAS",
    topicZh: "稀土",
    topicEn: "Rare earths",
  },
  {
    slug: "jingfei-deng-39491f",
    nameZh: "邓璟菲",
    nameEn: "Jingfei Deng",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "xin-deng-629e72",
    nameZh: "邓昕",
    nameEn: "Xin Deng",
    affiliation: "Huazhong Agricultural University",
    topicZh: "蔬菜",
    topicEn: "Vegetables",
  },
  {
    slug: "jingqi-dong-050554",
    nameZh: "董璟琦",
    nameEn: "Jingqi Dong",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "xize-dong-327e28",
    nameZh: "董曦泽",
    nameEn: "Xize Dong",
    affiliation: "Dalian University of Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "hao-dou-01e816",
    nameZh: "窦昊",
    nameEn: "Hao Dou",
    affiliation: "Cornell Engineering",
    topicZh: "锂电池",
    topicEn: "Lithium-ion battery",
  },
  {
    slug: "zhenhan-duan-000000",
    nameZh: "段振菡",
    nameEn: "Zhenhan Duan",
    affiliation: "South China Institute of Environmental Science",
    topicZh: "填埋",
    topicEn: "Landfilling",
  },
  {
    slug: "xiaoxu-duan-ef8911",
    nameZh: "段孝旭",
    nameEn: "Xiaoxu Duan",
    affiliation: "Sichuan University",
    topicZh: "含油污泥处理",
    topicEn: "Oily sludge treatment",
  },
  {
    slug: "mingyang-feng-19baa2",
    nameZh: "冯明阳",
    nameEn: "Mingyang Feng",
    affiliation: "Northeastern University",
    topicZh: "钢材生产",
    topicEn: "Steel production",
  },
  {
    slug: "chen-feng-68ff23",
    nameZh: "冯晨",
    nameEn: "Chen Feng",
    affiliation: "Tsinghua University",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "shiwen-gong-d0b9fa",
    nameZh: "宫诗雯",
    nameEn: "Shiwen Gong",
    affiliation: "Fudan University",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "dungang-gu-cf3c77",
    nameZh: "顾敦罡",
    nameEn: "Dungang Gu",
    affiliation: "Shanghai University Of Engineering Science",
    topicZh: "膜技术、污水处理",
    topicEn: "Membrane; Sewage disposal",
  },
  {
    slug: "qianwen-gu-ee77e2",
    nameZh: "顾倩雯",
    nameEn: "Qianwen Gu",
    affiliation: "Donghua University",
    topicZh: "再生塑料",
    topicEn: "Recycled plastic",
  },
  {
    slug: "huijuan-guo-305e7a",
    nameZh: "郭慧娟",
    nameEn: "Huijuan Guo",
    affiliation: "Nanchang University",
    topicZh: "塑料",
    topicEn: "Plastics",
  },
  {
    slug: "cui-hang-f6af7e",
    nameZh: "崔航",
    nameEn: "Cui Hang",
    affiliation: "USST",
    topicZh: "碎石 沙子",
    topicEn: "Crushed stone; Sand",
  },
  {
    slug: "xiaxia-he-f15fcc",
    nameZh: "和夏夏",
    nameEn: "Xiaxia He",
    affiliation: "USST",
    topicZh: "玻璃",
    topicEn: "Glass",
  },
  {
    slug: "tingting-hu-203640",
    nameZh: "胡婷莛",
    nameEn: "Tingting Hu",
    affiliation: "Shanghai University Of Engineering Science",
    topicZh: "过程直接排放核算",
    topicEn: "Process direct emission accounting",
  },
  {
    slug: "xiaoyu-huang-1c5555",
    nameZh: "黄小娱",
    nameEn: "Xiaoyu Huang",
    affiliation: "Chinese Research Academy of Environmental Sciences",
    topicZh: "光伏、氢能",
    topicEn: "photovoltaic, hydrogen",
  },
  {
    slug: "zixuan-huang-4c0b40",
    nameZh: "黄子轩",
    nameEn: "Zixuan Huang",
    affiliation: "SouthWest Petroleum University",
    topicZh: "含油污泥处理",
    topicEn: "Oily sludge treatment",
  },
  {
    slug: "yue-huang-a7e6d3",
    nameZh: "黄悦",
    nameEn: "Yue Huang",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "runyao-huang-f5b826",
    nameZh: "黄润垚",
    nameEn: "Runyao Huang",
    affiliation: "Tongji University",
    topicZh: "污水处理厂",
    topicEn: "Wastewater treatment",
  },
  {
    slug: "yujie-jia-ee183a",
    nameZh: "贾雨洁",
    nameEn: "Yujie Jia",
    affiliation: "Chongqing University",
    topicZh: "塑料回收",
    topicEn: "Plastic recycling",
  },
  {
    slug: "yanxin-jin-5e177b",
    nameZh: "金延鑫",
    nameEn: "Yanxin Jin",
    affiliation: "Beijing University of Chemical Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "sitian-jin-8e9fe5",
    nameZh: "金思甜",
    nameEn: "Sitian Jin",
    affiliation: "Tongji University",
    topicZh: "污水处理厂",
    topicEn: "Wastewater treatment",
  },
  {
    slug: "shikang-kang-e25e74",
    nameZh: "康诗康",
    nameEn: "Shikang Kang",
    affiliation: "CUMTB",
    topicZh: "化石燃料生产",
    topicEn: "Fossil fuel production",
  },
  {
    slug: "mingyan-ke-62ffe1",
    nameZh: "柯铭彦",
    nameEn: "Mingyan Ke",
    affiliation: "Jinan University",
    topicZh: "农药",
    topicEn: "Pesticide",
  },
  {
    slug: "qiushuang-lei-278a7b",
    nameZh: "雷秋霜",
    nameEn: "Qiushuang Lei",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "xianglan-li-000000",
    nameZh: "李香兰",
    nameEn: "Xianglan Li",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "hui-li-00dc80",
    nameZh: "李慧",
    nameEn: "Hui Li",
    affiliation: "Beijing Normal University",
    topicZh: "光电",
    topicEn: "Solar power",
  },
  {
    slug: "zongyu-li-0ee9fc",
    nameZh: "李宗昱",
    nameEn: "Zongyu Li",
    affiliation: "",
    topicZh: "固态电池",
    topicEn: "power battery",
  },
  {
    slug: "xingyong-li-4aeba3",
    nameZh: "李兴永",
    nameEn: "Xingyong Li",
    affiliation: "Beijing Normal University",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "zhiwei-li-55aa92",
    nameZh: "李智伟",
    nameEn: "Zhiwei Li",
    affiliation: "Hefei University of Technology",
    topicZh: "塑料",
    topicEn: "Plastic",
  },
  {
    slug: "yan-li-58ad17",
    nameZh: "李晏",
    nameEn: "Yan Li",
    affiliation: "China University of Geosciences Beijing",
    topicZh: "能源低碳政策与电力市场",
    topicEn: "Low-carbon energy policy and electricity market",
  },
  {
    slug: "xiao-li-595168",
    nameZh: "李晓",
    nameEn: "Xiao Li",
    affiliation: "Fudan University",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "mengru-li-66bfbf",
    nameZh: "李梦茹",
    nameEn: "Mengru Li",
    affiliation: "The Hong Kong University of Science and Technology",
    topicZh: "氨气",
    topicEn: "Ammonia",
  },
  {
    slug: "cheng-li-96565f",
    nameZh: "李城",
    nameEn: "Cheng Li",
    affiliation: "Donghua University",
    topicZh: "再生塑料",
    topicEn: "Recycled plastic",
  },
  {
    slug: "zimeng-li-99861b",
    nameZh: "李梓萌",
    nameEn: "Zimeng Li",
    affiliation: "China University of Mining & Technology - Beijing",
    topicZh: "化石燃料生产",
    topicEn: "Fossil fuel production",
  },
  {
    slug: "jian-li-a122df",
    nameZh: "李俭",
    nameEn: "Jian Li",
    affiliation: "Yangtze University",
    topicZh: "含油污泥处理",
    topicEn: "Oily sludge treatment",
  },
  {
    slug: "fangling-li-b41509",
    nameZh: "李方伶",
    nameEn: "Fangling Li",
    affiliation: "Tsinghua University",
    topicZh: "保温材料",
    topicEn: "Insulation material",
  },
  {
    slug: "xinyao-li-bc93a0",
    nameZh: "李昕遥",
    nameEn: "Xinyao Li",
    affiliation: "Minzu University of China",
    topicZh: "生活垃圾全过程管理",
    topicEn: "Integrated process management of municipal solid waste",
  },
  {
    slug: "zimeng-li-ed3477",
    nameZh: "李梓萌",
    nameEn: "Zimeng Li",
    affiliation: "CUMTB",
    topicZh: "化石燃料生产",
    topicEn: "Fossil fuel production",
  },
  {
    slug: "kailingli-liao-561dd8",
    nameZh: "廖恺玲俐",
    nameEn: "Kailingli Liao",
    affiliation: "Tsinghua University",
    topicZh: "农药，染料",
    topicEn: "Dye; Pesticide",
  },
  {
    slug: "min-liao-dbc1e5",
    nameZh: "廖敏",
    nameEn: "Min Liao",
    affiliation: "Xiamen University",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "wei-lin-028700",
    nameZh: "林维",
    nameEn: "Wei Lin",
    affiliation: "Beijing Institute of Technology",
    topicZh: "再生水、雨水",
    topicEn: "Reclaimed water, rainwater",
  },
  {
    slug: "xiaohua-liu-008f98",
    nameZh: "刘晓华",
    nameEn: "Xiaohua Liu",
    affiliation: "Shanghai University of Engineering Science",
    topicZh: "水处理",
    topicEn: "Water treatment",
  },
  {
    slug: "lili-liu-135149",
    nameZh: "刘利利",
    nameEn: "Lili Liu",
    affiliation: "China University of Geosciences Beijing",
    topicZh: "能源低碳政策与电力市场",
    topicEn: "Low-carbon energy policy and electricity market",
  },
  {
    slug: "jie-liu-1fbe76",
    nameZh: "刘杰",
    nameEn: "Jie Liu",
    affiliation: "SouthWest Petroleum University",
    topicZh: "含油污泥处理",
    topicEn: "Oily sludge treatment",
  },
  {
    slug: "yaotian-liu-5f40ca",
    nameZh: "刘耀天",
    nameEn: "Yaotian Liu",
    affiliation: "University of Sheffield",
    topicZh: "动力电池",
    topicEn: "动力电池",
  },
  {
    slug: "guangxin-liu-aea36d",
    nameZh: "刘广鑫",
    nameEn: "Guangxin Liu",
    affiliation: "Nanchang University",
    topicZh: "塑料",
    topicEn: "Plastics",
  },
  {
    slug: "chaoshuo-liu-bf6344",
    nameZh: "刘超硕",
    nameEn: "Chaoshuo Liu",
    affiliation: "Jilin University",
    topicZh: "生物质发电",
    topicEn: "Biomass Generation",
  },
  {
    slug: "xiaoyang-liu-cef49c",
    nameZh: "刘晓洋",
    nameEn: "Xiaoyang Liu",
    affiliation: "Dalian University of Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "yuqong-long-dd4fb7",
    nameZh: "龙宇琼",
    nameEn: "Yuqong Long",
    affiliation: "USST",
    topicZh: "建材",
    topicEn: "Building materials",
  },
  {
    slug: "hao-meng-78a08d",
    nameZh: "孟豪",
    nameEn: "Hao Meng",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "qiuci-miao-0cac16",
    nameZh: "苗秋慈",
    nameEn: "Qiuci Miao",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "xiaohang-ni-4205a5",
    nameZh: "倪晓航",
    nameEn: "Xiaohang Ni",
    affiliation: "Tongji University",
    topicZh: "污水处理厂",
    topicEn: "Wastewater treatment",
  },
  {
    slug: "dongliang-pan-49fa08",
    nameZh: "潘东亮",
    nameEn: "Dongliang Pan",
    affiliation: "SouthWest Petroleum University",
    topicZh: "含油污泥处理",
    topicEn: "Oily sludge treatment",
  },
  {
    slug: "mingyue-pang-3c15c5",
    nameZh: "庞明月",
    nameEn: "Mingyue Pang",
    affiliation: "Beijing Normal University",
    topicZh: "小水电",
    topicEn: "Small hydropower",
  },
  {
    slug: "chunhui-sang-2f6c01",
    nameZh: "桑春晖",
    nameEn: "Chunhui Sang",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "wenrui-shi-d06b6b",
    nameZh: "石文睿",
    nameEn: "Wenrui Shi",
    affiliation: "Hong Kong Baptist University",
    topicZh: "页岩气",
    topicEn: "Shale gas",
  },
  {
    slug: "zhihao-su-0a6256",
    nameZh: "苏志豪",
    nameEn: "Zhihao Su",
    affiliation: "SouthWest Petroleum University",
    topicZh: "含油污泥处理",
    topicEn: "Oily sludge treatment",
  },
  {
    slug: "zifan-sun-2b6e7e",
    nameZh: "孙子凡",
    nameEn: "Zifan Sun",
    affiliation: "Beijing University of Chemical Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "junlan-tang-6f6a31",
    nameZh: "唐君兰",
    nameEn: "Junlan Tang",
    affiliation: "Donghua University",
    topicZh: "再生塑料",
    topicEn: "Recycled plastic",
  },
  {
    slug: "tao-wang-000000",
    nameZh: "汪涛",
    nameEn: "Tao Wang",
    affiliation: "IUE, CAS",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "haoran-wang-00c333",
    nameZh: "王浩然",
    nameEn: "Haoran Wang",
    affiliation: "China University of Geosciences Beijing",
    topicZh: "能源低碳政策与电力市场",
    topicEn: "Low-carbon energy policy and electricity market",
  },
  {
    slug: "panbo-wang-086c1e",
    nameZh: "王攀博",
    nameEn: "Panbo Wang",
    affiliation: "Dalian University of Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "qiaochu-wang-0bbe43",
    nameZh: "王翘楚",
    nameEn: "Qiaochu Wang",
    affiliation: "IUE, CAS",
    topicZh: "有色金属",
    topicEn: "Non-ferrous metals",
  },
  {
    slug: "xiaojing-wang-236013",
    nameZh: "王晓静",
    nameEn: "Xiaojing Wang",
    affiliation: "East China Normal University",
    topicZh: "铜",
    topicEn: "copper",
  },
  {
    slug: "guiyun-wang-2b305c",
    nameZh: "王贵云",
    nameEn: "Guiyun Wang",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "nan-wang-2de8fd",
    nameZh: "王楠",
    nameEn: "Nan Wang",
    affiliation: "Shandong University",
    topicZh: "光伏",
    topicEn: "Photovoltaics",
  },
  {
    slug: "tao-wang-61d958",
    nameZh: "汪涛",
    nameEn: "Tao Wang",
    affiliation: "Institute of Urban Environment, Chinese Academy of Sciences",
    topicZh: "稀土",
    topicEn: "Rare Earths",
  },
  {
    slug: "mengyuan-wang-65d01b",
    nameZh: "王梦园",
    nameEn: "Mengyuan Wang",
    affiliation: "Beijing University of Chemical Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "peng-wang-9619e5",
    nameZh: "王鹏",
    nameEn: "Peng Wang",
    affiliation: "IUE, CAS",
    topicZh: "铜",
    topicEn: "Copper",
  },
  {
    slug: "jiqian-wang-98424c",
    nameZh: "王骥仟",
    nameEn: "Jiqian Wang",
    affiliation: "Beijing University of Chemical Technology",
    topicZh: "生物医药",
    topicEn: "biological medicine",
  },
  {
    slug: "xiaoqi-wang-a27616",
    nameZh: "王筱琪",
    nameEn: "Xiaoqi Wang",
    affiliation: "Hong Kong Baptist University",
    topicZh: "页岩气",
    topicEn: "Shale gas",
  },
  {
    slug: "baodi-wang-c8a974",
    nameZh: "王宝笛",
    nameEn: "Baodi Wang",
    affiliation: "Beijing University of Chemical Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "xiangjing-wang-d3b805",
    nameZh: "王湘锦",
    nameEn: "Xiangjing Wang",
    affiliation: "USST",
    topicZh: "砖块",
    topicEn: "Brick",
  },
  {
    slug: "jiayi-wang-e95d7c",
    nameZh: "王佳艺",
    nameEn: "Jiayi Wang",
    affiliation: "Sichuan University",
    topicZh: "含油污泥处理",
    topicEn: "Oily sludge treatment",
  },
  {
    slug: "hanlei-wang-ebc507",
    nameZh: "王韩磊",
    nameEn: "Hanlei Wang",
    affiliation: "Guangdong University of Technology",
    topicZh: "火力发电",
    topicEn: "Thermal power",
  },
  {
    slug: "peng-wang-ff4661",
    nameZh: "王鹏",
    nameEn: "Peng Wang",
    affiliation: "Institute of Urban Environment, Chinese Academy of Sciences",
    topicZh: "铜",
    topicEn: "Copper",
  },
  {
    slug: "fanghua-wei-2a3d6b",
    nameZh: "魏芳华",
    nameEn: "Fanghua Wei",
    affiliation: "Dalian University of Technology",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "renhao-wei-476d34",
    nameZh: "魏仁皓",
    nameEn: "Renhao Wei",
    affiliation: "Huazhong Agricultural University",
    topicZh: "水果、蔬菜、坚果",
    topicEn: "Fruit; Vegetables; Nut",
  },
  {
    slug: "kangni-wu-54a447",
    nameZh: "吴康妮",
    nameEn: "Kangni Wu",
    affiliation: "Xiamen University",
    topicZh: "海水养殖",
    topicEn: "Mariculture",
  },
  {
    slug: "meng-xiao-3854a5",
    nameZh: "肖萌",
    nameEn: "Meng Xiao",
    affiliation: "Chinese Academy of Environmental Planning",
    topicZh: "土壤和地下水修复管控",
    topicEn: "Soil and Groundwater remediation and control",
  },
  {
    slug: "yutong-xie-a7a5f0",
    nameZh: "谢雨桐",
    nameEn: "Yutong Xie",
    affiliation: "Chongqing University",
    topicZh: "生活垃圾",
    topicEn: "Household garbage",
  },
  {
    slug: "xin-xiong-713e0c",
    nameZh: "熊欣",
    nameEn: "Xin Xiong",
    affiliation: "Beijing Normal University",
    topicZh: "粮食",
    topicEn: "Grain",
  },
  {
    slug: "qianrong-xu-49478f",
    nameZh: "徐钱榕",
    nameEn: "Qianrong Xu",
    affiliation: "Tongji University",
    topicZh: "污水处理厂",
    topicEn: "Wastewater treatment",
  },
  {
    slug: "mengjie-xu-804cf1",
    nameZh: "徐梦洁",
    nameEn: "Mengjie Xu",
    affiliation: "Xiamen University",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "rui-yang-a3271d",
    nameZh: "杨瑞",
    nameEn: "Rui Yang",
    affiliation: "Wuhan University",
    topicZh: "畜禽",
    topicEn: "Livestock and poultry",
  },
  {
    slug: "xijing-yao-815e75",
    nameZh: "姚玺婧",
    nameEn: "Xijing Yao",
    affiliation: "Shandong University",
    topicZh: "光伏",
    topicEn: "Photovoltaics",
  },
  {
    slug: "xiaoyu-yi-0d6b74",
    nameZh: "伊晓昱",
    nameEn: "Xiaoyu Yi",
    affiliation: "Northeastern University",
    topicZh: "钢材生产",
    topicEn: "Steel production",
  },
  {
    slug: "linlin-yin-000000",
    nameZh: "尹琳琳",
    nameEn: "Linlin Yin",
    affiliation: "CUMTB",
    topicZh: "化石燃料生产",
    topicEn: "Fossil fuel production",
  },
  {
    slug: "linlin-yin-486c04",
    nameZh: "尹琳琳",
    nameEn: "Linlin Yin",
    affiliation: "China University of Mining & Technology - Beijing",
    topicZh: "化石燃料生产",
    topicEn: "Fossil fuel production",
  },
  {
    slug: "chenyang-yu-5110f6",
    nameZh: "于晨阳",
    nameEn: "Chenyang Yu",
    affiliation: "Tongji University",
    topicZh: "污水处理厂",
    topicEn: "Wastewater treatment",
  },
  {
    slug: "jingjing-zhang-300cc6",
    nameZh: "张净晶",
    nameEn: "Jingjing Zhang",
    affiliation: "IGSNRR, CAS",
    topicZh: "航空燃油",
    topicEn: "Bio-jet fuel",
  },
  {
    slug: "juchao-zhang-502dfb",
    nameZh: "张炬超",
    nameEn: "Juchao Zhang",
    affiliation: "East China Normal University",
    topicZh: "化学品",
    topicEn: "Chemicals",
  },
  {
    slug: "yaodan-zhang-625e5a",
    nameZh: "张耀丹",
    nameEn: "Yaodan Zhang",
    affiliation: "Xiamen University",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "na-zhang-a74859",
    nameZh: "张娜",
    nameEn: "Na Zhang",
    affiliation: "Huazhong Agricultural University",
    topicZh: "水果、蔬菜、坚果",
    topicEn: "Fruit; Vegetables; Nut",
  },
  {
    slug: "yixuan-zhang-aadfdc",
    nameZh: "张艺璇",
    nameEn: "Yixuan Zhang",
    affiliation: "IGSNRR, CAS",
    topicZh: "航空燃油",
    topicEn: "Bio-jet fuel",
  },
  {
    slug: "bingqian-zhang-bd9b99",
    nameZh: "张冰倩",
    nameEn: "Bingqian Zhang",
    affiliation: "Tsinghua University",
    topicZh: "锂电池",
    topicEn: "Lithium-ion battery",
  },
  {
    slug: "keshuo-zhang-d8ac05",
    nameZh: "张可硕",
    nameEn: "Keshuo Zhang",
    affiliation: "Jinan University",
    topicZh: "抽水储能",
    topicEn: "Pumped hydro energy storage",
  },
  {
    slug: "haoran-zhang-e3298a",
    nameZh: "张浩然",
    nameEn: "Haoran Zhang",
    affiliation: "Wuhan University",
    topicZh: "作物",
    topicEn: "Crops",
  },
  {
    slug: "xinpeng-zheng-3a7c29",
    nameZh: "郑新鹏",
    nameEn: "Xinpeng Zheng",
    affiliation: "Northeastern University",
    topicZh: "钢材生产",
    topicEn: "Steel production",
  },
  {
    slug: "wangrui-zheng-cae6f6",
    nameZh: "郑王睿",
    nameEn: "Wangrui Zheng",
    affiliation: "Beijing Normal University",
    topicZh: "奶制品",
    topicEn: "Dairy product",
  },
  {
    slug: "cheng-zhong-61d317",
    nameZh: "钟诚",
    nameEn: "Cheng Zhong",
    affiliation: "China University of Geosciences Beijing",
    topicZh: "能源低碳政策与电力市场",
    topicEn: "Low-carbon energy policy and electricity market",
  },
  {
    slug: "ruixi-zhu-49733d",
    nameZh: "朱睿希",
    nameEn: "Ruixi Zhu",
    affiliation: "CUMTB",
    topicZh: "化石燃料生产",
    topicEn: "Fossil fuel production",
  },
  {
    slug: "xian-zhu-9d1fa6",
    nameZh: "朱娴",
    nameEn: "Xian Zhu",
    affiliation: "Huazhong Agricultural University",
    topicZh: "水果、蔬菜、坚果",
    topicEn: "Fruit; Vegetables; Nut",
  },
  {
    slug: "yi-cao-a224a0",
    nameZh: "曹祎",
    nameEn: "Yi Cao",
    affiliation: "Tsinghua University",
    topicZh: "工具开发",
    topicEn: "工具开发",
  },
  {
    slug: "zhihao-chen-27d475",
    nameZh: "陈郅昊",
    nameEn: "Zhihao Chen",
    affiliation: "University of Shanghai for Science and Technology",
    topicZh: "建材",
    topicEn: "building materials",
  },
  {
    slug: "hang-cui-e5607c",
    nameZh: "崔航",
    nameEn: "Hang Cui",
    affiliation: "University of Shanghai for Science and Technology",
    topicZh: "碎石 沙子",
    topicEn: "Crushed stone; sand",
  },
  {
    slug: "xiaxia-he-a1cb62",
    nameZh: "和夏夏",
    nameEn: "Xiaxia He",
    affiliation: "University of Shanghai for Science and Technology",
    topicZh: "玻璃",
    topicEn: "Glass",
  },
  {
    slug: "shikang-kang-4529d6",
    nameZh: "康诗康",
    nameEn: "Shikang Kang",
    affiliation: "China University of Mining & Technology - Beijing",
    topicZh: "化石燃料生产",
    topicEn: "Fossil fuel production",
  },
  {
    slug: "xiao-li-902ea4",
    nameZh: "李晓",
    nameEn: "Xiao Li",
    affiliation: "Fudan University",
    topicZh: "",
    topicEn: "",
  },
  {
    slug: "yuqong-long-bc25ed",
    nameZh: "龙宇琼",
    nameEn: "Yuqong Long",
    affiliation: "University of Shanghai for Science and Technology",
    topicZh: "建材",
    topicEn: "building materials",
  },
  {
    slug: "qiao-chu-wang-6bf415",
    nameZh: "王翘楚",
    nameEn: "Qiao-Chu Wang",
    affiliation: "Institute of Urban Environment, Chinese Academy of Sciences",
    topicZh: "有色金属",
    topicEn: "Non-ferrous metals",
  },
  {
    slug: "hanlei-wang-77dd67",
    nameZh: "王韩磊",
    nameEn: "Hanlei Wang",
    affiliation: "Guangdong University of Technology",
    topicZh: "火力发电",
    topicEn: "Thermal power",
  },
  {
    slug: "xiangjing-wang-979183",
    nameZh: "王湘锦",
    nameEn: "Xiangjing Wang",
    affiliation: "University of Shanghai for Science and Technology",
    topicZh: "砖块",
    topicEn: "Brick",
  },
  {
    slug: "ruixi-zhu-d397fa",
    nameZh: "朱睿希",
    nameEn: "Ruixi Zhu",
    affiliation: "China University of Mining & Technology - Beijing",
    topicZh: "化石燃料生产",
    topicEn: "Fossil fuel production",
  },
] as const;

export const partnerInstitutions = [
  {
    nameZh: "阿德莱德大学",
    nameEn: "University of Adelaide",
    logo: "/community/partners/partner-01.svg",
  },
  {
    nameZh: "北京服装学院",
    nameEn: "Beijing Institute of Fashion Technology",
    logo: "/community/partners/partner-02.webp",
  },
  {
    nameZh: "北京化工大学",
    nameEn: "Beijing University of Chemical Technology",
    logo: "/community/partners/partner-03.webp",
  },
  {
    nameZh: "北京林业大学",
    nameEn: "Beijing Forestry University",
    logo: "/community/partners/partner-04.webp",
  },
  {
    nameZh: "北京理工大学",
    nameEn: "Beijing Institute of Technology",
    logo: "/community/partners/partner-05.webp",
  },
  {
    nameZh: "北京师范大学",
    nameEn: "Beijing Normal University",
    logo: "/community/partners/partner-06.webp",
  },
  {
    nameZh: "北京信息科技大学",
    nameEn: "Beijing Information Science and Technology University",
    logo: "/community/partners/partner-07.webp",
  },
  { nameZh: "长江大学", nameEn: "Yangtze University", logo: "/community/partners/partner-08.webp" },
  {
    nameZh: "大连理工大学",
    nameEn: "Dalian University of Technology",
    logo: "/community/partners/partner-09.webp",
  },
  {
    nameZh: "东北大学",
    nameEn: "Northeastern University",
    logo: "/community/partners/partner-10.webp",
  },
  { nameZh: "东华大学", nameEn: "Donghua University", logo: "/community/partners/partner-11.webp" },
  { nameZh: "复旦大学", nameEn: "Fudan University", logo: "/community/partners/partner-12.webp" },
  {
    nameZh: "格罗宁根大学",
    nameEn: "University of Groningen",
    logo: "/community/partners/partner-13.svg",
  },
  {
    nameZh: "广东工业大学",
    nameEn: "Guangdong University of Technology",
    logo: "/community/partners/partner-14.webp",
  },
  { nameZh: "广西大学", nameEn: "Guangxi University", logo: "/community/partners/partner-15.png" },
  { nameZh: "贵州大学", nameEn: "Guizhou University", logo: "/community/partners/partner-16.webp" },
  { nameZh: "河北大学", nameEn: "Hebei University", logo: "/community/partners/partner-17.webp" },
  {
    nameZh: "合肥工业大学",
    nameEn: "Hefei University of Technology",
    logo: "/community/partners/partner-18.webp",
  },
  {
    nameZh: "华东师范大学",
    nameEn: "East China Normal University",
    logo: "/community/partners/partner-19.webp",
  },
  {
    nameZh: "华中科技大学",
    nameEn: "Huazhong University of Science and Technology",
    logo: "/community/partners/partner-20.webp",
  },
  {
    nameZh: "华中农业大学",
    nameEn: "Huazhong Agricultural University",
    logo: "/community/partners/partner-21.webp",
  },
  { nameZh: "吉林大学", nameEn: "Jilin University", logo: "/community/partners/partner-22.webp" },
  { nameZh: "暨南大学", nameEn: "Jinan University", logo: "/community/partners/partner-23.webp" },
  { nameZh: "莱顿大学", nameEn: "Leiden University", logo: "/community/partners/partner-24.webp" },
  {
    nameZh: "密歇根大学",
    nameEn: "University of Michigan",
    logo: "/community/partners/partner-25.svg",
  },
  {
    nameZh: "南昌大学",
    nameEn: "Nanchang University",
    logo: "/community/partners/partner-26.webp",
  },
  {
    nameZh: "南方科技大学",
    nameEn: "Southern University of Science and Technology",
    logo: "/community/partners/partner-27.webp",
  },
  {
    nameZh: "南京航空航天大学",
    nameEn: "Nanjing University of Aeronautics and Astronautics",
    logo: "/community/partners/partner-28.webp",
  },
  { nameZh: "南开大学", nameEn: "Nankai University", logo: "/community/partners/partner-29.webp" },
  {
    nameZh: "纽约州立大学",
    nameEn: "State University of New York",
    logo: "/community/partners/partner-30.webp",
  },
  {
    nameZh: "帕多瓦大学",
    nameEn: "University of Padua",
    logo: "/community/partners/partner-31.webp",
  },
  {
    nameZh: "清华大学",
    nameEn: "Tsinghua University",
    logo: "/community/partners/partner-32.webp",
  },
  {
    nameZh: "清华苏州环境创新研究院",
    nameEn: "Research Institute for Environmental Innovation (Suzhou), Tsinghua University",
    logo: "/community/partners/partner-33.webp",
  },
  {
    nameZh: "上海大学",
    nameEn: "Shanghai University",
    logo: "/community/partners/partner-34.webp",
  },
  {
    nameZh: "上海第二工业大学",
    nameEn: "Shanghai Polytechnic University",
    logo: "/community/partners/partner-35.webp",
  },
  {
    nameZh: "上海工程技术大学",
    nameEn: "Shanghai University Of Engineering Science",
    logo: "/community/partners/partner-36.webp",
  },
  {
    nameZh: "上海理工大学",
    nameEn: "University of Shanghai for Science and Technology",
    logo: "/community/partners/partner-37.webp",
  },
  {
    nameZh: "上海市环境科学研究院",
    nameEn: "Shanghai Academy of Environmental Sciences",
    logo: "/community/partners/partner-38.webp",
  },
  {
    nameZh: "山东大学",
    nameEn: "Shandong University",
    logo: "/community/partners/partner-39.webp",
  },
  { nameZh: "厦门大学", nameEn: "Xiamen University", logo: "/community/partners/partner-40.webp" },
  {
    nameZh: "生态环境部环境规划院",
    nameEn: "Chinese Academy of Environmental Planning",
    logo: "/community/partners/partner-41.webp",
  },
  {
    nameZh: "生态环境部华南环境科学研究所",
    nameEn: "South China Institute of Environmental Science",
    logo: "/community/partners/partner-42.webp",
  },
  { nameZh: "四川大学", nameEn: "Sichuan University", logo: "/community/partners/partner-43.webp" },
  {
    nameZh: "太原理工大学",
    nameEn: "Taiyuan University of Technology",
    logo: "/community/partners/partner-44.webp",
  },
  { nameZh: "天津大学", nameEn: "Tianjin University", logo: "/community/partners/partner-45.webp" },
  { nameZh: "同济大学", nameEn: "Tongji University", logo: "/community/partners/partner-46.webp" },
  { nameZh: "武汉大学", nameEn: "Wuhan University", logo: "/community/partners/partner-47.webp" },
  {
    nameZh: "香港城市大学",
    nameEn: "City University of Hong Kong",
    logo: "/community/partners/partner-48.webp",
  },
  {
    nameZh: "香港浸会大学",
    nameEn: "Hong Kong Baptist University",
    logo: "/community/partners/partner-49.webp",
  },
  {
    nameZh: "香港科技大学",
    nameEn: "The Hong Kong University of Science and Technology",
    logo: "/community/partners/partner-50.webp",
  },
  {
    nameZh: "湘湖实验室",
    nameEn: "Xianghu Laboratory",
    logo: "/community/partners/partner-51.webp",
  },
  {
    nameZh: "谢菲尔德大学",
    nameEn: "University of Sheffield",
    logo: "/community/partners/partner-52.webp",
  },
  {
    nameZh: "西安交通大学",
    nameEn: "Xi’an Jiaotong University",
    logo: "/community/partners/partner-53.webp",
  },
  {
    nameZh: "西南交通大学",
    nameEn: "Southwest Jiaotong University",
    logo: "/community/partners/partner-54.webp",
  },
  {
    nameZh: "西南石油大学",
    nameEn: "SouthWest Petroleum University",
    logo: "/community/partners/partner-55.webp",
  },
  {
    nameZh: "英属哥伦比亚大学",
    nameEn: "University of British Columbia",
    logo: "/community/partners/partner-56.webp",
  },
  {
    nameZh: "浙江大学",
    nameEn: "Zhejiang University",
    logo: "/community/partners/partner-57.webp",
  },
  {
    nameZh: "浙江理工大学",
    nameEn: "Zhejiang Sci-Tech University",
    logo: "/community/partners/partner-58.webp",
  },
  {
    nameZh: "中国标准化研究院",
    nameEn: "China National Institute of Standardization",
    logo: "/community/partners/partner-59.webp",
  },
  {
    nameZh: "中国地质大学（北京）",
    nameEn: "China University of Geosciences Beijing",
    logo: "/community/partners/partner-60.webp",
  },
  {
    nameZh: "中国环境科学研究院",
    nameEn: "Chinese Research Academy of Environmental Sciences",
    logo: "/community/partners/partner-61.webp",
  },
  {
    nameZh: "中国科学院城市环境研究所",
    nameEn: "Institute of Urban Environment, Chinese Academy of Sciences",
    logo: "/community/partners/partner-62.webp",
  },
  {
    nameZh: "中国科学院地理科学与资源研究所",
    nameEn: "Institute of Geographic Sciences and Natural Resources Research",
    logo: "/community/partners/partner-63.webp",
  },
  {
    nameZh: "中国矿业大学（北京）",
    nameEn: "China University of Mining & Technology - Beijing",
    logo: "/community/partners/partner-64.webp",
  },
  {
    nameZh: "中国林业科学研究院",
    nameEn: "Chinese Academy of Forestry",
    logo: "/community/partners/partner-65.webp",
  },
  {
    nameZh: "中国民航大学",
    nameEn: "Civil Aviation University of China",
    logo: "/community/partners/partner-66.webp",
  },
  {
    nameZh: "中国石油大学(北京)",
    nameEn: "China University of Petroleum, Beijing",
    logo: "/community/partners/partner-67.webp",
  },
  {
    nameZh: "重庆大学",
    nameEn: "Chongqing University",
    logo: "/community/partners/partner-68.webp",
  },
  {
    nameZh: "中央民族大学",
    nameEn: "Minzu University of China",
    logo: "/community/partners/partner-69.webp",
  },
] as const;
