/**
 * Members follow the Wix page's rendered reading order: top to bottom,
 * and left to right within each row. Wix stores the repeater column by column,
 * so its DOM order is intentionally not used here.
 */
export const teamMembers = [
  {
    slug: "ming-xu",
    name: "Ming Xu",
    role: "founder",
    institution: "tsinghua",
    email: "xu-ming@tsinghua.edu.cn",
  },
  {
    slug: "sangwon-suh",
    name: "Sangwon Suh",
    role: "chairProfessor",
    institution: "tsinghua",
    email: undefined,
  },
  {
    slug: "nan-li",
    name: "Nan Li",
    role: "techLead",
    institution: "tsinghua",
    email: "li-nan@tsinghua.edu.cn",
  },
  {
    slug: "jianchuan-qi",
    name: "Jianchuan Qi",
    role: "operationsLead",
    institution: "tsinghua",
    email: "jcqi@tsinghua.edu.cn",
  },
  {
    slug: "huimin-chang",
    name: "Huimin Chang",
    role: "dataLead",
    institution: "tsinghua",
    email: "huiminchang@tsinghua.edu.cn",
  },
  {
    slug: "jing-guo",
    name: "Jing Guo",
    role: "aiScientist",
    institution: "tsinghua",
    email: "guo_jing@tsinghua.edu.cn",
  },
  {
    slug: "yuanyi-huang",
    name: "Yuanyi Huang",
    role: "devopsManager",
    institution: "tsinghua",
    email: "hyuanyi87@foxmail.com",
  },
  {
    slug: "bixuan-wu",
    name: "Bixuan Wu",
    role: "policySpecialist",
    institution: "riet",
    email: "bixuan.wu@tsinghua-riet.com",
  },
  {
    slug: "ying-zheng",
    name: "Ying Zheng",
    role: "policySpecialist",
    institution: "riet",
    email: "jennytei@126.com",
  },
  {
    slug: "yan-qin",
    name: "Yan Qin",
    role: "policySpecialist",
    institution: "riet",
    email: "yan.qin@hotmail.com",
  },
  {
    slug: "yushi-chen",
    name: "Yushi Chen",
    role: "policySpecialist",
    institution: "riet",
    email: "yushichenchn@163.com",
  },
  {
    slug: "jinbiao-lyu",
    name: "Jinbiao Lyu",
    role: "newEnergyIndustrySpecialist",
    institution: "riet",
    email: "Lyujinbiao@163.com",
  },
  {
    slug: "chenling-fu",
    name: "Chenling Fu",
    role: "contentManager",
    institution: "tsinghua",
    email: "fu-chenling@tsinghua.edu.cn",
  },
  {
    slug: "yi-cao",
    name: "Yi Cao",
    role: "softwareEngineer",
    institution: "bistu",
    email: "tgenkidu@163.com",
  },
  {
    slug: "ruoxi-xiong",
    name: "Ruoxi Xiong",
    role: "supportSpecialist",
    institution: "tsinghua",
    email: "xiongrx23@mails.tsinghua.edu.cn",
  },
  {
    slug: "zimeng-cai",
    name: "Zimeng Cai",
    role: "dataQualitySpecialist",
    institution: "tsinghua",
    email: "caizm23@mails.tsinghua.edu.cn",
  },
  {
    slug: "si-zhang",
    name: "Si Zhang",
    role: "dataQualitySpecialist",
    institution: "muc",
    email: "22300087@muc.edu.cn",
  },
  {
    slug: "jiayi-yuan",
    name: "Jiayi Yuan",
    role: "communityCoordinator",
    institution: "bnu",
    email: "Jiayi_Y@mail.bnu.edu.cn",
  },
  {
    slug: "ziqi-wang",
    name: "Ziqi Wang",
    role: "communityCoordinator",
    institution: "tsinghua",
    email: "w-zq20@mails.tsinghua.edu.cn",
  },
  {
    slug: "chao-zhang",
    name: "Chao Zhang",
    role: "editorialSpecialist",
    institution: "bnu",
    email: "202011180043@mail.bnu.edu.cn",
  },
  {
    slug: "ayazhan-nurpeiis",
    name: "Ayazhan Nurpeiis",
    role: "editorialSpecialist",
    institution: "tsinghua",
    email: "jiez23@mails.tsinghua.edu.cn",
  },
  {
    slug: "bin-shui",
    name: "Bin Shui",
    role: "editorialSpecialist",
    institution: "cityu",
    email: "bshui2-c@my.cityu.edu.hk",
  },
  {
    slug: "ruiqiao-li",
    name: "Ruiqiao Li",
    role: "editorialSpecialist",
    institution: "tsinghua",
    email: "2017301040050@whu.edu.cn",
  },
] as const;

export const teamInstitutionCount = new Set(teamMembers.map((member) => member.institution)).size;

export const teamEnsembleMembers = teamMembers;
