import * as THREE from "three";
import landPoints from "../land-points.json";
import type { OpticalKit } from "./optical-kit";

/** Real geographic point geometry; the point sprite is generated by the optical kit. */
export function createWorldMap(parent: THREE.Group, kit: OpticalKit) {
  const geometry = new THREE.BufferGeometry().setFromPoints(
    landPoints.map(
      ([x = 0, z = 0], i) =>
        new THREE.Vector3(x * 1.13, 0.018 + Math.abs(Math.sin(i * 37.1)) * 0.025, z * 1.25),
    ),
  );
  const colors = landPoints.flatMap((_, i) => {
    const brightness = 0.7 + Math.abs(Math.sin(i * 19.7)) * 0.6;
    return [brightness, brightness, brightness];
  });
  geometry.setAttribute("color", new THREE.Float32BufferAttribute(colors, 3));
  const map = new THREE.Points(
    geometry,
    kit.tint(
      new THREE.PointsMaterial({
        color: 0xc6abe8,
        size: 2.05,
        sizeAttenuation: false,
        vertexColors: true,
        map: kit.dot,
        transparent: true,
        alphaTest: 0.03,
        opacity: 0.98,
        depthWrite: false,
        toneMapped: false,
      }),
      4,
      "node",
    ),
  );
  map.position.set(0.25, 0, 0.25);
  map.name = "Geographic point cloud";
  map.rotation.y = 0.9;
  parent.add(map);
  return map;
}
