import * as THREE from "three";
import landPoints from "../land-points.json";
import type { OpticalKit } from "./optical-kit";

/** Real geographic point geometry; the point sprite is generated by the optical kit. */
export function createWorldMap(parent: THREE.Group, kit: OpticalKit) {
  const geometry = new THREE.BufferGeometry().setFromPoints(
    landPoints.map(([x = 0, z = 0], i) => {
      const horizontal = x * 1.18 + z * 0.7 + 0.38;
      const depth = z * 1.75 + 1.0;
      // Skew along the plate's diagonal and compress outer corners smoothly.
      // A positive radial derivative keeps islands distinct near the cut edge.
      const reach = Math.abs(horizontal) + Math.abs(depth);
      const extent = reach > 2.25 ? 2.25 + 0.55 * (1 - Math.exp(-(reach - 2.25) / 0.55)) : reach;
      const fit = reach > 0 ? extent / reach : 1;
      return new THREE.Vector3(
        ((horizontal + depth) * fit) / Math.SQRT2,
        0.018 + Math.abs(Math.sin(i * 37.1)) * 0.025,
        ((depth - horizontal) * fit) / Math.SQRT2,
      );
    }),
  );
  const colors = landPoints.flatMap((_, i) => {
    const brightness = 0.7 + Math.abs(Math.sin(i * 19.7)) * 0.6;
    return [brightness, brightness, brightness];
  });
  geometry.setAttribute("color", new THREE.Float32BufferAttribute(colors, 3));
  const map = new THREE.Points(
    geometry,
    kit.tint(
      new THREE.PointsMaterial({
        color: 0xc6abe8,
        size: 2.05,
        sizeAttenuation: false,
        vertexColors: true,
        map: kit.dot,
        transparent: true,
        alphaTest: 0.03,
        opacity: 0.98,
        depthWrite: false,
        toneMapped: false,
      }),
      4,
      "node",
    ),
  );
  map.name = "Geographic point cloud";
  parent.add(map);
  return map;
}
