import * as THREE from "three";
import landPoints from "../land-points.json";
import type { OpticalKit } from "./optical-kit";

/** Real geographic point geometry; the point sprite is generated by the optical kit. */
export function createWorldMap(parent: THREE.Group, kit: OpticalKit) {
  const map = new THREE.Points(
    new THREE.BufferGeometry().setFromPoints(
      landPoints.map(([x = 0, z = 0]) => new THREE.Vector3(x * 0.99, 0.027, z * 1.44)),
    ),
    kit.tint(
      new THREE.PointsMaterial({
        color: 0xc6abe8,
        size: 1.8,
        sizeAttenuation: false,
        map: kit.dot,
        transparent: true,
        alphaTest: 0.03,
        opacity: 0.8,
        depthWrite: false,
        toneMapped: false,
      }),
      4,
      "node",
    ),
  );
  map.position.set(0.15, 0, 0.15);
  map.name = "Geographic point cloud";
  map.rotation.y = Math.PI / 4 - 0.1;
  parent.add(map);
  return map;
}
